# Generated by Django 3.0.6 on 2020-05-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memid', models.CharField(max_length=20)),
                ('passwd', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ZipTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=7)),
                ('area1', models.CharField(max_length=10)),
                ('area2', models.CharField(max_length=20)),
                ('area3', models.CharField(max_length=30)),
                ('area4', models.CharField(max_length=50)),
            ],
        ),
    ]
